// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGwoS-tZEhy_BoeZyQfkDYRow9pdDf89Q',
    appId: '1:1060482862322:web:8fe7c5708a7edd4151546b',
    messagingSenderId: '1060482862322',
    projectId: 'hotelanchor',
    authDomain: 'hotelanchor.firebaseapp.com',
    storageBucket: 'hotelanchor.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Eqf4f0K2CfSvyZk8YE48s_9wW7__ags',
    appId: '1:1060482862322:ios:a9c674fbfb1d05b051546b',
    messagingSenderId: '1060482862322',
    projectId: 'hotelanchor',
    storageBucket: 'hotelanchor.firebasestorage.app',
    iosBundleId: 'com.example.hotelanchor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGwoS-tZEhy_BoeZyQfkDYRow9pdDf89Q',
    appId: '1:1060482862322:web:9eab372d70148ab951546b',
    messagingSenderId: '1060482862322',
    projectId: 'hotelanchor',
    authDomain: 'hotelanchor.firebaseapp.com',
    storageBucket: 'hotelanchor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDllwTxv06zIhGrbqV7REkuNp7e8wht6nA',
    appId: '1:48234802689:ios:a948cb815f998054005a00',
    messagingSenderId: '48234802689',
    projectId: 'hotel-anchor',
    storageBucket: 'hotel-anchor.firebasestorage.app',
    iosBundleId: 'com.example.hotelanchor',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZctMRRA29nvbsF-UX1mOv7Gybxh0hg38',
    appId: '1:48234802689:android:101c4d8d3a0efe7b005a00',
    messagingSenderId: '48234802689',
    projectId: 'hotel-anchor',
    storageBucket: 'hotel-anchor.firebasestorage.app',
  );

}